version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: netflixdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netflixdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netflixdb"]
      interval: 5s
      timeout: 3s
      retries: 5

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile # O Dockerfile do Luigi na raiz
    container_name: netflix_pipeline
    command: tail -f /dev/null
    tty: true
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER:-postgresql+psycopg2://postgres:postgres@db:5432/netflixdb}
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy

  dashboard:
    build: 
      context: ./src/scripts/dashboard
      dockerfile: Dockerfile
    container_name: netflix_visualizacao
    ports:
      - "8501:8501"
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=netflixdb
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./src/scripts/dashboard:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: