version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: netflixdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netflixdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netflixdb"]
      interval: 5s
      timeout: 3s
      retries: 5

  pipeline:
    build:
      context: ./src/scripts/dashboard
      dockerfile: Dockerfile
    command: tail -f /dev/null
    tty: true
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER:-postgresql+psycopg2://postgres:postgres@db:5432/netflixdb}
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
  dashboard:
    build: 
      context: .
      dockerfile: src/scripts/dashboard/Dockerfile # O Docker diz onde está o manual
    container_name: netflix_visualizacao
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src # Compartilha o código
    depends_on:
      - db

volumes:
  db_data:
